adding functions to control runner in copy mode
preservim/vimux pull request #156
Opened 2017-09-02 01:49 UTC by juchem

these functions allow entering copy mode without switching panes/windows
they also allow sending keystrokes to control the copy mode buffer

2017-09-12 14:21 UTC, ostera commented
Oh this looks interesting! Give us some time to have a look and we'll get back to it :)

2021-02-13 16:46 UTC, alerque requested changes
Thanks for taking the time to contribute this. It does look like a useful addition, but can I trouble you to add documentation to the help file so other users know it exists and can figure out how to use it properly?

2021-02-26 21:57 UTC, closed without merging

2021-03-18 14:50 UTC, alerque commented
Don't think this will be useful for others? Don't use VIM or TMUX any more? Just don't have the bandwidth to document?

2021-03-22 16:16 UTC, juchem commented
@alerque no bandwidth.