Optionally return up-arrow functionality to VimuxPromptCommand
preservim/vimux pull request #190
Opened 2021-03-10 14:22 UTC by jaspertandy

#188 Having whatever 'shellcmd' does makes Vimux unusable for me. I don't know what shellcmd is doing here and I can't see any documentation on why it was added, but I'm guessing I wasn't using it before so I would like the option to have the old behaviour back. I guess this means you lose autocomplete or something, which I never had, so I can live without that.

2021-03-16 09:22 UTC, alerque requested changes
Sorry to mess up your workflow! Clearly myself and the person that requested this have different workflows. Given that I don't seen an easy way to have *both* sets of features (shell completion vs. vim command editing), this looks like a decent compromise. Can I ask you add a note to the docs so people can discover how to set this?

2021-03-16 09:23 UTC, alerque commented
For reference this happened in #142, there is some discussion and background there.

2021-03-18 13:50 UTC, jaspertandy commented
@alerque no worries - turned out to be a small amount of trial and error to see what had introduced the issue for me! Everyone's workflow is different, and this is still useful; I just didn't realise how much I used up arrow in VimuxPromptCommand until it was gone!

I've pushed an entry to the docs, detailing this variable and its effect. Let me know if you need anything more elsewhere.

2021-03-18 13:50 UTC, alerque approved these changes

2021-03-18 13:51 UTC, merged